apiVersion: v1
kind: Secret
metadata:
  name: encryption-key
  namespace: default  # Vous pouvez choisir un autre namespace si nécessaire
type: Opaque
data:
  encryption-key: Xp9KVNFi1gUTisj8rRvDTMc1naz1JbHAzxIR6+m4vJQ=  
